---
profilepic: 
name: Ramzi
surname: Guerbaa
position: "PhD student"
address: "Institut Supérieur des Sciences Biologiques Appliquées de Tunis"
phone: +216 50 455 027 
email: "guerbaaramzi2014@gmail.com"
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
headcolor: 990000
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Interests

 * Antimicrobial resistance, Antimicrobial Peptides, Gut microbiota.
 * Molecular cloning, gene disruption, whole genome characterization.
 * Comparative Genomics, Genomic Epidemiology.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "PhD in Food Science", "2019-2023", "ISSBAT/Université Laval", "Tunis/Québec, TUNISIA/CANADA",
  "Master in Microbiology", "2015-2018", "Faculty of Sciences", "Tunis, TUNISIA",
  "Bachelor in Biotechnology", "2012-2015", "ISSBAT", "Tunis, TUNISIA"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```


```{r, eval=FALSE}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```


```{r, eval=FALSE}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

